/** High-contrast pixel palette (GDD §9). Near-black void, sparse neons. */
export const Palette = {
  void: 0x05070a,
  probeBody: 0xc8e7ff,
  thruster: 0x3d7cff,
  sensorEye: 0x7cffd4,
  hunter: 0xff5a4a,
  ambusher: 0xff9a3c,
  pointB: 0x5ee0ff,
  hud: 0x8aa0b4,
  hudWarn: 0xffc14a,
  cover: 0x1a2433,
  coverEdge: 0x3a4d66,
  pocket: 0x0a1016,
  hull: 0xff6b6b,
  wellRim: 0xc45a6a,
  wellField: 0x5a2a44,
  shortcut: 0xff8a5a,
  longWay: 0x4a7a8a,
  bulwark: 0xc45a6a,
  swarmling: 0xffc14a,
  splitter: 0xff8a3a,
  bolt: 0x7cffd4,
  anomaly: 0x7c5cff,
  echo: 0xc89aff,
  echoPrime: 0xe0a0ff,
  invert: 0xff6ad5,
  gate: 0x8a3a4a,
  ward: 0xff8a5a,
} as const;

export const World = {
  width: 1280,
  height: 720,
} as const;

export const SceneKey = {
  Boot: 'Boot',
  Preload: 'Preload',
  Drift: 'Drift',
  DebrisField: 'DebrisField',
  GravityWell: 'GravityWell',
  Swarm: 'Swarm',
  Anomaly: 'Anomaly',
  BossGate: 'BossGate',
  Test: 'Test',
} as const;

export const TextureKey = {
  Probe: 'probe',
  Hunter: 'hunter',
  Ambusher: 'ambusher',
  Bulwark: 'bulwark',
  GateBulwark: 'gate-bulwark',
  Swarmling: 'swarmling',
  Splitter: 'splitter',
  Bolt: 'bolt',
  Echo: 'echo',
  EchoPrime: 'echo-prime',
  WardBolt: 'ward-bolt',
  PointA: 'point-a',
  PointB: 'point-b',
  WellCore: 'well-core',
  Cover: 'cover-steel',
  CoverDebris: 'cover-debris',
  CoverAnomaly: 'cover-anomaly',
  CoverGate: 'cover-gate',
  PocketFloor: 'pocket-floor',
  ZoneFloor: 'zone-floor',
  ZoneFloorWarm: 'zone-floor-warm',
  ZoneFloorAnomaly: 'zone-floor-anomaly',
  ZoneFloorGate: 'zone-floor-gate',
  Lane: 'lane',
  LaneAnomaly: 'lane-anomaly',
  LaneGate: 'lane-gate',
  GateWall: 'gate-wall',
  GateWallOpen: 'gate-wall-open',
} as const;

/** Theme lock (GDD §1). */
export const THEME_LINE = 'You are not a hero. You are a probe. You do not return.';
